# Generated by Django 3.0.5 on 2020-05-02 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_first_name', models.CharField(max_length=40)),
                ('Teacher_second_name', models.CharField(max_length=20)),
                ('Teacher_specializatin', models.CharField(max_length=20)),
                ('Teacher_birthday', models.DateField(default=datetime.date(2020, 5, 2))),
            ],
        ),
    ]
