# Generated by Django 3.0.5 on 2020-05-04 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 4)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_specializatin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
