# Generated by Django 3.0.5 on 2020-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200504_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_specializatin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
