# Generated by Django 3.0.5 on 2020-05-04 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200504_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=40)),
                ('Group_specializatin', models.CharField(max_length=10, null=True)),
                ('Group_creation_date', models.DateField(default=datetime.date(2020, 5, 4))),
            ],
        ),
    ]
