# Generated by Django 3.0.5 on 2020-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Group_size',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
