# Generated by Django 3.0.5 on 2020-05-13 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_groups_group_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 13)),
        ),
    ]
