# Generated by Django 3.0.5 on 2020-05-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200513_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 16)),
        ),
    ]
