# Generated by Django 3.0.5 on 2020-05-16 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20200516_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_specializatin',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
    ]
