# Generated by Django 3.0.5 on 2020-05-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_teacher_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 27)),
        ),
    ]
