# Generated by Django 3.0.5 on 2020-05-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20200527_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_group',
        ),
    ]
