# Generated by Django 3.0.5 on 2020-05-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0009_auto_20200528_1555'),
        ('teacher', '0012_remove_teacher_teacher_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Teacher_group',
            field=models.ManyToManyField(null=True, related_name='groups', to='Group.Groups'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 5, 28)),
        ),
    ]
