# Generated by Django 3.0.5 on 2020-05-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20200528_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_group',
        ),
    ]
