# Generated by Django 3.0.5 on 2020-06-02 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_remove_teacher_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 6, 2)),
        ),
    ]
