# Generated by Django 3.0.5 on 2020-06-13 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20200605_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_birthday',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
    ]
