# Generated by Django 3.0.5 on 2020-05-13 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=40)),
                ('Group_specializatin', models.CharField(max_length=10, null=True)),
                ('Group_size', models.IntegerField(default=0, max_length=3)),
                ('Group_creation_date', models.DateField(default=datetime.date(2020, 5, 13))),
            ],
        ),
    ]
