# Generated by Django 3.0.5 on 2020-05-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='Group_specializatin',
            new_name='Group_specialization',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='Group_name',
        ),
    ]
