# Generated by Django 3.0.5 on 2020-05-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0005_auto_20200524_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('floor', models.SmallIntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groups',
            name='Group_creation_date',
            field=models.DateField(default=datetime.date(2020, 5, 27)),
        ),
        migrations.AddField(
            model_name='groups',
            name='classroom',
            field=models.ManyToManyField(null=True, related_name='groups', to='Group.Classroom'),
        ),
    ]
