# Generated by Django 3.0.5 on 2020-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_remove_teacher_teacher_group'),
        ('Group', '0007_groups_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='Group_teacher',
        ),
        migrations.AddField(
            model_name='groups',
            name='Group_teacher',
            field=models.ManyToManyField(null=True, related_name='teachers', to='teacher.Teacher'),
        ),
    ]
