# Generated by Django 3.0.5 on 2020-05-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0008_auto_20200527_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='Group_teacher',
        ),
        migrations.AlterField(
            model_name='groups',
            name='Group_creation_date',
            field=models.DateField(default=datetime.date(2020, 5, 28)),
        ),
    ]
