# Generated by Django 3.0.5 on 2020-06-02 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20200602_2012'),
        ('Group', '0010_groups_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Group_creation_date',
            field=models.DateField(default=datetime.date(2020, 6, 2)),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Group_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='classroom',
            field=models.ManyToManyField(null=True, related_name='classroom', to='Group.Classroom'),
        ),
    ]
