# Generated by Django 3.0.5 on 2020-06-05 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0011_auto_20200602_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Group_creation_date',
            field=models.DateField(default=datetime.date(2020, 6, 5)),
        ),
    ]
