# Generated by Django 3.0.5 on 2020-05-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200516_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
