# Generated by Django 3.0.5 on 2020-05-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200516_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
