# Generated by Django 3.0.5 on 2020-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200517_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
