# Generated by Django 3.0.5 on 2020-05-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0005_auto_20200524_0907'),
        ('student', '0005_student_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Group.Groups'),
        ),
    ]
