# Generated by Django 3.0.5 on 2020-05-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_auto_20200527_1411'),
        ('student', '0006_student_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Group.Groups'),
        ),
    ]
