# Generated by Django 3.0.5 on 2020-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0009_auto_20200528_1555'),
        ('student', '0007_auto_20200527_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_group',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_group',
            field=models.ManyToManyField(null=True, related_name='students', to='Group.Groups'),
        ),
    ]
