# Generated by Django 3.0.5 on 2020-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200528_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
